### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [itzmeanjan/weatherz#1]
Hello @itzmeanjan  again.. 😊here's my design for weatherZ. I hope you like it!

![weatherZ pres-02](https://user-images.githubusercontent.com/36028424/57669666-7dac3b00-763e-11e9-9fa3-810305414253.png)

readme mock up
![read](https://user-images.githubusercontent.com/36028424/57669671-83a21c00-763e-11e9-9231-7e2f1b4dbeb2.png)

**Comment by itzmeanjan** [comment]
Nice work @Tobaloidee :heart: 

Like your design, please submit a PR :)

**Comment by Tobaloidee** [comment]
here's the PR #2 @itzmeanjan  and below is the link for other versions & file formats

[DOWNLOAD](https://drive.google.com/drive/u/1/folders/1BZkD5onyFTj6RR7Q_utnUV7-CoBRZgX5)

Will go on with the other projects again..Thanks!  👍😊

**Comment by itzmeanjan** [comment]
Merging done @Tobaloidee 

Great work :+1: Hope to see you in next project :heart:
